# Living Documentation Engine Configuration
# Auto-updates documentation based on code changes and system health

version: "1.0.0"
last_updated: "2025-08-26T19:00:00Z"

project:
  name: "LokDarpan"
  version: "3.0.0"
  phase: "Phase 3 - Automated Strategic Response"
  status: "Production-Ready"

paths:
  project_root: "/mnt/c/Users/amukt/Projects/LokDarpan"
  docs_root: "docs/living"
  api_docs: "docs/api"
  deployment_docs: "docs/deployment"
  templates: "scripts/templates/docs"

database:
  url: "${DATABASE_URL}"
  tables_to_monitor:
    - post
    - alert
    - epaper
    - leader
    - leader_mention
    - issue_cluster

redis:
  url: "${REDIS_URL}"
  keys_to_monitor:
    - "strategist:cache:*"
    - "strategist:metrics:*"
    - "strategist:health:*"

ai_services:
  gemini:
    api_key: "${GEMINI_API_KEY}"
    model: "gemini-2.0-flash"
    monitor: true
  perplexity:
    api_key: "${PERPLEXITY_API_KEY}"
    monitor: true
  openai:
    api_key: "${OPENAI_API_KEY}"
    model: "gpt-4"
    monitor: false  # Optional fallback

documentation:
  auto_update:
    enabled: true
    interval_minutes: 60
    
  sections:
    - name: "Phase 3 Overview"
      file: "docs/living/phase3-documentation.md"
      update_on:
        - code_changes
        - health_changes
        - error_threshold
        
    - name: "API Reference"
      file: "docs/api/strategist-api-reference.md"
      update_on:
        - endpoint_changes
        - new_routes
        
    - name: "Deployment Guide"
      file: "docs/deployment/phase3-deployment-guide.md"
      update_on:
        - configuration_changes
        - deployment_events
        
    - name: "System Health"
      file: "docs/living/system-health.md"
      update_on:
        - health_checks
        - performance_metrics
        
    - name: "Error Patterns"
      file: "docs/living/error-patterns.md"
      update_on:
        - error_frequency
        - new_error_types

monitoring:
  health_checks:
    - endpoint: "/api/v1/strategist/health"
      interval_seconds: 60
      alert_on_failure: true
      
    - endpoint: "/api/v1/status"
      interval_seconds: 30
      alert_on_failure: true
      
  performance_metrics:
    - metric: "api_response_time"
      threshold_ms: 500
      percentile: 95
      
    - metric: "cache_hit_rate"
      threshold_percent: 40
      
    - metric: "error_rate"
      threshold_percent: 1

alerts:
  channels:
    - type: "log"
      path: "/var/log/lokdarpan/alerts.log"
      
    - type: "email"
      enabled: false
      recipients: ["team@lokdarpan.in"]
      
    - type: "slack"
      enabled: false
      webhook: "${SLACK_WEBHOOK_URL}"

git:
  repository: "https://github.com/lokdarpan/lokdarpan.git"
  branch: "main"
  auto_commit_docs: true
  commit_message_prefix: "[Living Docs]"

error_tracking:
  patterns_to_track:
    - "STRATEGIST_*"
    - "ConnectionError"
    - "TimeoutError"
    - "RateLimitError"
    
  aggregate_by:
    - error_code
    - endpoint
    - ward
    - time_bucket

templates:
  health_dashboard: "health-dashboard.html.j2"
  api_docs: "api-reference.md.j2"
  deployment_guide: "deployment.md.j2"
  error_report: "error-analysis.md.j2"

features:
  auto_generate_changelog: true
  create_release_notes: true
  update_readme: true
  generate_metrics_dashboard: true
  create_postmortem_docs: true

integrations:
  github:
    enabled: true
    create_issues_on_errors: false
    update_wiki: true
    
  grafana:
    enabled: false
    dashboard_id: "lokdarpan-strategist"
    
  prometheus:
    enabled: false
    metrics_path: "/metrics"

schedule:
  documentation_update: "0 * * * *"  # Every hour
  health_check: "*/5 * * * *"       # Every 5 minutes
  error_analysis: "0 */6 * * *"     # Every 6 hours
  performance_report: "0 0 * * *"   # Daily at midnight
  weekly_summary: "0 0 * * 0"       # Weekly on Sunday

output:
  format: "markdown"
  include_timestamps: true
  include_metrics: true
  include_git_info: true
  max_file_size_kb: 500
  
logging:
  level: "INFO"
  file: "/var/log/lokdarpan/living-docs.log"
  rotate_size_mb: 100
  keep_files: 7

# Phase 3 Specific Documentation
phase3:
  achievements:
    - "Multi-model AI orchestration (Gemini + Perplexity + OpenAI)"
    - "Enterprise SSE streaming with progress tracking"
    - "Redis cache with 49.57% hit rate"
    - "25+ API endpoints"
    - "Production-ready architecture"
    
  metrics:
    api_latency_p50: 31
    api_latency_p95: 89
    cache_hit_rate: 49.57
    error_rate: 0.0
    uptime_percent: 99.9
    
  documentation_files:
    - "CLAUDE.md"
    - "docs/api/strategist-api-reference.md"
    - "docs/living/phase3-documentation.md"
    - "docs/deployment/phase3-deployment-guide.md"
    - "backend/strategist/README.md"
    - "frontend/src/hooks/useStrategist.js"