# LokDarpan Political Intelligence Platform - Alert Rules
# Critical alerts for production monitoring during political campaigns

groups:
  - name: lokdarpan.critical
    rules:
      # High-priority alerts for campaign-critical functionality
      - alert: LokDarpanBackendDown
        expr: up{job="lokdarpan-backend"} == 0
        for: 30s
        labels:
          severity: critical
          component: backend
        annotations:
          summary: "LokDarpan Backend is down"
          description: "The LokDarpan backend API has been down for more than 30 seconds. This affects all political intelligence operations."

      - alert: DatabaseConnectionFailure
        expr: up{job="postgres"} == 0
        for: 1m
        labels:
          severity: critical
          component: database
        annotations:
          summary: "PostgreSQL database is unreachable"
          description: "Database connectivity lost for {{ $labels.instance }}. All data operations are affected."

      - alert: HighAPIResponseTime
        expr: histogram_quantile(0.95, rate(flask_http_request_duration_seconds_bucket[5m])) > 2
        for: 2m
        labels:
          severity: warning
          component: api
        annotations:
          summary: "API response time is high"
          description: "95th percentile response time is {{ $value }}s, exceeding 2s threshold. This may impact user experience during critical campaign periods."

      - alert: AIServiceFailure
        expr: increase(lokdarpan_ai_service_errors_total[5m]) > 5
        for: 1m
        labels:
          severity: high
          component: ai-services
        annotations:
          summary: "Political Strategist AI services experiencing failures"
          description: "{{ $value }} AI service errors in the last 5 minutes. Political analysis capabilities may be impacted."

  - name: lokdarpan.performance
    rules:
      # Performance-related alerts for optimal campaign operations
      - alert: HighCPUUsage
        expr: 100 * (1 - avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m]))) > 80
        for: 5m
        labels:
          severity: warning
          component: system
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is {{ $value }}% on {{ $labels.instance }}. Consider scaling up resources."

      - alert: HighMemoryUsage
        expr: 100 * (1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) > 85
        for: 3m
        labels:
          severity: warning
          component: system
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is {{ $value }}% on {{ $labels.instance }}. System may become unresponsive."

      - alert: DiskSpaceRunningLow
        expr: 100 * (1 - node_filesystem_avail_bytes / node_filesystem_size_bytes) > 85
        for: 2m
        labels:
          severity: warning
          component: storage
        annotations:
          summary: "Disk space running low"
          description: "Disk usage is {{ $value }}% on {{ $labels.instance }}:{{ $labels.mountpoint }}."

      - alert: DatabaseConnectionsHigh
        expr: postgresql_active_connections / postgresql_max_connections > 0.8
        for: 2m
        labels:
          severity: warning
          component: database
        annotations:
          summary: "Database connection pool is nearly exhausted"
          description: "Active connections: {{ $value }}. Database may start refusing connections."

  - name: lokdarpan.application
    rules:
      # Application-specific alerts for political intelligence operations
      - alert: HighErrorRate
        expr: rate(flask_http_requests_total{status=~"5.."}[5m]) > 0.1
        for: 2m
        labels:
          severity: high
          component: application
        annotations:
          summary: "High application error rate"
          description: "Error rate is {{ $value }} errors/second. Application stability is compromised."

      - alert: CeleryWorkerDown
        expr: celery_workers_active == 0
        for: 1m
        labels:
          severity: high
          component: background-tasks
        annotations:
          summary: "No active Celery workers"
          description: "Background task processing has stopped. News ingestion and AI analysis will be delayed."

      - alert: RedisConnectionFailure
        expr: up{job="redis"} == 0
        for: 30s
        labels:
          severity: high
          component: cache
        annotations:
          summary: "Redis cache is down"
          description: "Redis connectivity lost. Caching and session management are affected."

      - alert: PoliticalStrategistTimeout
        expr: increase(lokdarpan_ai_analysis_timeout_total[10m]) > 3
        for: 1m
        labels:
          severity: high
          component: political-strategist
        annotations:
          summary: "Political Strategist analysis timeouts"
          description: "{{ $value }} analysis timeouts in 10 minutes. AI analysis may be overloaded or external services are slow."

  - name: lokdarpan.security
    rules:
      # Security-related alerts for campaign data protection
      - alert: SuspiciousAPIActivity
        expr: rate(flask_http_requests_total{status="401"}[5m]) > 2
        for: 2m
        labels:
          severity: warning
          component: security
        annotations:
          summary: "High rate of unauthorized API requests"
          description: "{{ $value }} unauthorized requests/second. Possible brute force attack."

      - alert: DatabaseSlowQueries
        expr: postgresql_slow_queries > 10
        for: 1m
        labels:
          severity: warning
          component: database-security
        annotations:
          summary: "Database experiencing slow queries"
          description: "{{ $value }} slow queries detected. May indicate inefficient queries or potential SQL injection attempts."

  - name: lokdarpan.campaign-critical
    rules:
      # Campaign-specific alerts for critical political intelligence periods
      - alert: NewsIngestionStopped
        expr: increase(lokdarpan_news_articles_processed_total[15m]) == 0
        for: 10m
        labels:
          severity: high
          component: news-ingestion
        annotations:
          summary: "News ingestion has stopped"
          description: "No news articles processed in the last 15 minutes. Political intelligence may be stale."

      - alert: WardDataStale
        expr: time() - lokdarpan_ward_data_last_update > 3600
        for: 5m
        labels:
          severity: warning
          component: data-freshness
        annotations:
          summary: "Ward data is becoming stale"
          description: "Ward data hasn't been updated for {{ $value }} seconds. Political insights may be outdated."

      - alert: StrategistAnalysisBacklog
        expr: lokdarpan_pending_analysis_queue_size > 20
        for: 5m
        labels:
          severity: warning
          component: political-strategist
        annotations:
          summary: "Political analysis queue is backing up"
          description: "{{ $value }} analyses are queued. Campaign teams may experience delays in strategic insights."