"""Add created_at column to post table

Revision ID: 02ac3ac5b585
Revises: d4bdde590100
Create Date: 2025-08-12 12:01:26.898720

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '02ac3ac5b585'
down_revision = 'd4bdde590100'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ward', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('opportunities', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('threats', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('actionable_alerts', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('source_articles', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_alert_timestamp'))
        batch_op.create_index(batch_op.f('ix_alert_ward'), ['ward'], unique=False)
        batch_op.drop_column('timestamp')
        batch_op.drop_column('is_read')
        batch_op.drop_column('metric')
        batch_op.drop_column('ai_summary')
        batch_op.drop_column('change_description')

    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('text',
               existing_type=sa.TEXT(),
               type_=sa.String(length=280),
               existing_nullable=False)
        batch_op.alter_column('author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('timestamp')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('source')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.alter_column('author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('text',
               existing_type=sa.String(length=280),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.add_column(sa.Column('change_description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ai_summary', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('metric', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_alert_ward'))
        batch_op.create_index(batch_op.f('ix_alert_timestamp'), ['timestamp'], unique=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('source_articles')
        batch_op.drop_column('actionable_alerts')
        batch_op.drop_column('threats')
        batch_op.drop_column('opportunities')
        batch_op.drop_column('ward')

    # ### end Alembic commands ###
