"""Reintroduce epaper table

Revision ID: 51d8e8e4cc64
Revises: 93e55b319031
Create Date: 2025-08-15 10:50:08.294739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51d8e8e4cc64'
down_revision = '93e55b319031'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('epaper',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publication_name', sa.String(length=100), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('epaper', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_epaper_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_epaper_publication_date'), ['publication_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('epaper', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_epaper_publication_date'))
        batch_op.drop_index(batch_op.f('ix_epaper_created_at'))

    op.drop_table('epaper')
    # ### end Alembic commands ###
