"""Add Epaper model

Revision ID: a7d53cd7fd59
Revises: 02ac3ac5b585
Create Date: 2025-08-12 19:23:54.493421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7d53cd7fd59'
down_revision = '02ac3ac5b585'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('epaper',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publication_name', sa.String(length=100), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('epaper')
    # ### end Alembic commands ###
