"""Add email column to user table and align models

Revision ID: d4bdde590100
Revises: e638c78f4bee
Create Date: 2025-08-12 11:35:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd4bdde590100'
down_revision = 'e638c78f4bee'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Stage 1: Add the email column, but make it nullable for now
    op.add_column('user', sa.Column('email', sa.String(length=120), nullable=True))
    
    # Stage 2: Populate the new email column for any existing users
    # This ensures no rows are null. We generate a unique placeholder.
    op.execute("UPDATE \"user\" SET email = 'placeholder-' || id || '@lokdarpan.io' WHERE email IS NULL")
    
    # Stage 3: Now that all rows are populated, add the NOT NULL constraint
    op.alter_column('user', 'email', nullable=False)
    
    # Create a unique index on the email column
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###